version: "3"

services:
  nginx:
    image: linuxserver/letsencrypt:0.39.0-ls73
    volumes:
      - ./nginx.conf:/config/nginx/site-confs/default
      - nginx_volume:/config
    ports:
      - "443:443"
      - "80:80"
    networks:
      - monitor
    environment:
      - URL=cgjobsup.cigi.illinois.edu
      - EMAIL=zimox2@illinois.edu

networks:
  monitor:
    driver: bridge

volumes:
  nginx_volume:
