version: "3"

services:
  nginx:
    image: linuxserver/letsencrypt:0.39.0-ls73
    volumes:
      - ./nginx.conf:/config/nginx/site-confs/default
      - nginx_volume:/config
    network_mode: host
    environment:
      - URL=cgjobsup.cigi.illinois.edu
      - EMAIL=zimox2@illinois.edu

volumes:
  nginx_volume:
