version: "3"

services:
  nginx:
    image: linuxserver/letsencrypt:0.39.0-ls73
    volumes:
      - ./nginx.conf:/config/nginx/site-confs/default
      - nginx_volume:/config
    # network_mode is 'host' to allow nginx running inside container to 
    # access job sub node.js server running on host
    # Must manually open 80 and 443 on host firewall
    # Otherwise cert cannot be renewed automatically (Drew 01/01/2020)
    # ufw allow 80
    # ufw allow 443 
    restart: always
    network_mode: host
    environment:
      - URL=cgjobsup.cigi.illinois.edu
      - EMAIL=zimox2@illinois.edu

  redis:
    image: redis:5
    restart: always
    volumes:
    - redis-data:/data

  job_supervisor:
    image: node:10-slim-npm-alpine-node
    restart: always
    volumes:
    - ./:/job_supervisor

volumes:
  nginx_volume:
  redis-data:
