version: "3"

services:
  nginx:
    image: linuxserver/letsencrypt:0.39.0-ls73
    volumes:
      - ./nginx.conf:/config/nginx/site-confs/default
      - nginx_volume:/config
    # network_mode is 'host' to allow nginx running inside container to 
    # access job sub node.js server running on host
    # Must manually open 80 and 443 on host firewall
    # Otherwise cert cannot be renewed automatically (Drew 01/01/2020)
    # ufw allow 80
    # ufw allow 443 
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    environment:
      - URL=cgjobsup.cigi.illinois.edu
      - EMAIL=zimox2@illinois.edu

  job_supervisor:
    image: zimoxiao/job_supervisor:v0.0.2
    restart: on-failure
    volumes:
    - ./:/job_supervisor:rw
    privileged: true
    ports:
      - "3030:3030"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      OPENCONNECT_PASSWORD: ${OPENCONNECT_PASSWORD}
      OPENCONNECT_USER: ${OPENCONNECT_USER}
      OPENCONNECT_AUTHGROUP: ${OPENCONNECT_AUTHGROUP}
      OPENCONNECT_URL: ${OPENCONNECT_URL}
      OPENCONNECT_MFA_CODE: ${OPENCONNECT_MFA_CODE}

volumes:
  nginx_volume:
