name: BUILD PYTHON 3.6 IMAGE

on:
  push:
    branches:
      - master
      - v2
    paths:
      - 'default_images/python/3.6/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build Python 3.6
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./default_images/python/3.6
          push: true
          tags: zimoxiao/python_default:3.6