name: build-core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        npm config set registry http://registry.npmjs.org/
        npm config set //npm.pkg.github.com/:_authToken $TOKEN
        npm install
        npm run build
      env:
        TOKEN: ${{secrets.GITHUB_TOKEN}}
